language: php
php:
  - 7.4
services:
  - mysql
before_script:
  - echo 'APP_KEY=SomeRandomString >> .env'
  - mysql -e 'create database lycee_overture;'
  - composer self-update
  - composer install --no-interaction
script: vendor/bin/phpunit
